# Generated by Django 5.0.6 on 2024-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('username', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
